[workspace]
resolver = "3"
members = ["crates/*", "examples/*", "tools/proto-gen"]
default-members = [
    "crates/pvault",
    "crates/pvault-core",
    "crates/pvault-ipc",
    "crates/pvault-proto",
]

[workspace.package]
version = "1.0.0"
edition = "2024"
authors = ["vyPal"]
license = "GPL-3.0-or-later"
repository = "https://github.com/vyPal/PVault"

[workspace.dependencies]
pvault-core = { path = "crates/pvault-core", version = "1.0.0" }
pvault-proto = { path = "crates/pvault-proto", version = "1.0.0" }
pumpkin-plugin-api = { version = "0.1.0", git = "https://github.com/Pumpkin-MC/Pumpkin", package = "pumpkin-plugin-api" }
prost = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"

[profile.release]
lto = true
